/* borschik:include:./createApp.js */
/* borschik:include:./MainController.js */
/* borschik:include:./ModalController.js */
/* borschik:include:./ModalSegmentsController.js */
/* borschik:include:./TableController.js */
/* borschik:include:./PreviewDirective.js */
/* borschik:include:./LookalikeDirective.js */
/* borschik:include:./FormDirective.js */
/* borschik:include:./ColumnsService.js */
/* borschik:include:./bootstrapApp.js */