angular.module('app').filter('currency', ->
    map = { "ALL": "L"
        , "AFN": "؋"
        , "ARS": "$"
        , "AWG": "ƒ"
        , "AUD": "$"
        , "AZN": "₼"
        , "BSD": "$"
        , "BBD": "$"
        , "BYR": "p."
        , "BZD": "BZ$"
        , "BMD": "$"
        , "BOB": "Bs."
        , "BAM": "KM"
        , "BWP": "P"
        , "BGN": "лв"
        , "BRL": "R$"
        , "BND": "$"
        , "KHR": "៛"
        , "CAD": "$"
        , "KYD": "$"
        , "CLP": "$"
        , "CNY": "¥"
        , "COP": "$"
        , "CRC": "₡"
        , "HRK": "kn"
        , "CUP": "₱"
        , "CZK": "Kč"
        , "DKK": "kr"
        , "DOP": "RD$"
        , "XCD": "$"
        , "EGP": "£"
        , "SVC": "$"
        , "EEK": "kr"
        , "EUR": "€"
        , "FKP": "£"
        , "FJD": "$"
        , "GHC": "¢"
        , "GIP": "£"
        , "GTQ": "Q"
        , "GGP": "£"
        , "GYD": "$"
        , "HNL": "L"
        , "HKD": "$"
        , "HUF": "Ft"
        , "ISK": "kr"
        , "INR": "₹"
        , "IDR": "Rp"
        , "IRR": "﷼"
        , "IMP": "£"
        , "ILS": "₪"
        , "JMD": "J$"
        , "JPY": "¥"
        , "JEP": "£"
        , "KES": "KSh"
        , "KZT": "лв"
        , "KPW": "₩"
        , "KRW": "₩"
        , "KGS": "лв"
        , "LAK": "₭"
        , "LVL": "Ls"
        , "LBP": "£"
        , "LRD": "$"
        , "LTL": "Lt"
        , "MKD": "ден"
        , "MYR": "RM"
        , "MUR": "₨"
        , "MXN": "$"
        , "MNT": "₮"
        , "MZN": "MT"
        , "NAD": "$"
        , "NPR": "₨"
        , "ANG": "ƒ"
        , "NZD": "$"
        , "NIO": "C$"
        , "NGN": "₦"
        , "NOK": "kr"
        , "OMR": "﷼"
        , "PKR": "₨"
        , "PAB": "B/."
        , "PYG": "Gs"
        , "PEN": "S/."
        , "PHP": "₱"
        , "PLN": "zł"
        , "QAR": "﷼"
        , "RON": "lei"
        , "RUB": "р"
        , "SHP": "£"
        , "SAR": "﷼"
        , "RSD": "Дин."
        , "SCR": "₨"
        , "SGD": "$"
        , "SBD": "$"
        , "SOS": "S"
        , "ZAR": "R"
        , "LKR": "₨"
        , "SEK": "kr"
        , "CHF": "Fr."
        , "SRD": "$"
        , "SYP": "£"
        , "TZS": "TSh"
        , "TWD": "NT$"
        , "THB": "฿"
        , "TTD": "TT$"
        , "TRY": ""
        , "TRL": "₤"
        , "TVD": "$"
        , "UGX": "USh"
        , "UAH": "₴"
        , "GBP": "£"
        , "USD": "$"
        , "UYU": "$U"
        , "UZS": "лв"
        , "VEF": "Bs"
        , "VND": "₫"
        , "YER": "﷼"
        , "ZWD": "Z$"
    }
    (input, num = 2, postfix='USD') ->
        postfix = map[postfix] || '$'
        return (0 + ' ' + postfix) if !input
        return (jQuery.number(input, num, ',', ' ') + ' ' + postfix) if parseFloat(input)
).filter('number', ->
    (input, row, name) ->
        patternStr = '((\d+(\.|\,)\d*)|\d+)'
        input += ""
        matches = input.match(/((\d+(\.|\,)\d*)|\d+)/g)
        return input if matches is null
        return input.replace(/[^((\d+(\.|\,)\d*)|\d+)]/g, '').replace(/((\d+(\.|\,)\d*)|\d+)/g, (str, match1, match2, match3) ->
            str = str.replace(match3, '.')
            res = jQuery.number(str, (if angular.isDefined(match3) then 2 else 0), ',', ' ')
            return res
        )
)
