/* borschik:include:../../bower_components/jquery/jquery.js */
/* borschik:include:../../bower_components/angular/angular.min.js */
/* borschik:include:../../bower_components/bootstrap/dist/js/bootstrap.min.js */
/* borschik:include:../../bower_components/angular-bootstrap/ui-bootstrap.min.js */
/* borschik:include:../../bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js */
/* borschik:include:../../bower_components/csv-js/csv.js */
/* borschik:include:../../bower_components/pdfmake/build/pdfmake.js */
/* borschik:include:../../bower_components/pdfmake/build/vfs_fonts.js */
/* borschik:include:../../libs/ui-grid-unstable/ui-grid-unstable.min.js */
/* borschik:include:../../libs/bootstrapValidation/formValidation.min.js */
/* borschik:include:../../libs/bootstrapValidation/formValidation.bootstrap.min.js */
