// Generated by CoffeeScript 1.8.0
angular.module('app').controller('MainController', [
  '$scope', '$rootScope', '$modal', '$window', '$http', '$q', function($scope, $rootScope, $modal, $window, $http, $q) {
    $rootScope.preloading.page = false;
    $scope.openModal = function(size, mode) {
      var deferred, modalInstance;
      switch (mode) {
        case 'create':
        case 'edit':
          modalInstance = $modal.open({
            templateUrl: 'modal.html',
            controller: 'ModalController',
            size: size
          });
          modalInstance.mode = mode;
          break;
        case 'segments':
          $rootScope.preloading.page = true;
          deferred = $q.defer();
          $http.get("pixel/" + $rootScope.editedPixel.id + "/affinity").success(function(response) {
            return deferred.resolve(response);
          }).error(function(response) {
            return deferred.resolve({
              status: 'error',
              data: response
            });
          });
          modalInstance = $modal.open({
            templateUrl: 'modal__segments.html',
            controller: 'ModalSegmentsController',
            size: size,
            resolve: {
              segments: function() {
                return deferred.promise;
              }
            }
          });
      }
      return modalInstance.result.then(function(result) {
        return $scope.result = result;
      }, function() {
        console.info('Modal dismissed at  : ' + new Date());
        if (angular.isDefined($window.__postedPixel)) {
          delete $window.__postedPixel;
          return $rootScope.editedPixel = false;
        }
      });
    };
    if ($window.__user) {
      $rootScope.userName = $window.__user.company + ($window.__pixels.length + 1);
    }
    if (!$window.__pixels.length) {
      $scope.openModal('lg', 'create');
    }
    if (angular.isDefined($window.__postedPixel)) {
      $rootScope.editedPixel = $window.__postedPixel;
      return $scope.openModal('lg', 'edit');
    }
  }
]);
