// Generated by CoffeeScript 1.8.0
angular.module('app').controller('ModalSegmentsController', [
  '$scope', '$rootScope', '$modalInstance', 'segments', function($scope, $rootScope, $modalInstance, segments) {
    var message;
    $rootScope.preloading.page = false;
    $scope.modalTitle = "Similar Segments";
    console.info("Segments to show: ", segments);
    message = "Unknown error occured when requesting segments!";
    if (segments.status === 'success') {
      $scope.segments = segments.data;
      if (angular.isArray(segments.data) && !segments.data.length) {
        $scope.message = "No similar segments found";
      }
    } else {
      $scope.message = segments.message || message;
    }
    $scope.ok = function() {
      return $modalInstance.close();
    };
    return $scope.cancel = function() {
      return $modalInstance.dismiss('cancel');
    };
  }
]);
